# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  greeting:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - greeting
      - build:
          filters:
            branches:
              only:
                - staging
